package com.wulee.administrator.zuji.database.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "LOGIN_TABLE".
 */
public class LoginBean {

    private String mobile;
    private Long current_uid;
    private Boolean logining;
    private String session;

    public LoginBean() {
    }

    public LoginBean(String mobile, Long current_uid, Boolean logining, String session) {
        this.mobile = mobile;
        this.current_uid = current_uid;
        this.logining = logining;
        this.session = session;
    }

    public String getMobile() {
        return mobile;
    }

    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    public Long getCurrent_uid() {
        return current_uid;
    }

    public void setCurrent_uid(Long current_uid) {
        this.current_uid = current_uid;
    }

    public Boolean getLogining() {
        return logining;
    }

    public void setLogining(Boolean logining) {
        this.logining = logining;
    }

    public String getSession() {
        return session;
    }

    public void setSession(String session) {
        this.session = session;
    }

}
