package com.wulee.administrator.zuji.database.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "PERSONINFO_TABLE".
 */
public class PersonInfo {

    private String mobile;
    private String name;
    private String sex;
    private String birthday;
    private String address;
    private String header_img_url;

    public PersonInfo() {
    }

    public PersonInfo(String mobile) {
        this.mobile = mobile;
    }

    public PersonInfo(String mobile, String name, String sex, String birthday, String address, String header_img_url) {
        this.mobile = mobile;
        this.name = name;
        this.sex = sex;
        this.birthday = birthday;
        this.address = address;
        this.header_img_url = header_img_url;
    }

    public String getMobile() {
        return mobile;
    }

    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getSex() {
        return sex;
    }

    public void setSex(String sex) {
        this.sex = sex;
    }

    public String getBirthday() {
        return birthday;
    }

    public void setBirthday(String birthday) {
        this.birthday = birthday;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getHeader_img_url() {
        return header_img_url;
    }

    public void setHeader_img_url(String header_img_url) {
        this.header_img_url = header_img_url;
    }

}
